(+semver: fix) Update protoc usage to work with macOS and newer golang
syncromatics/kafmesh pull request #33
Opened 2021-05-01 02:19 UTC by annymsMthd

Signed-off-by: Joshua Benjamin <joshua.benjamin@iherb.com>

2021-05-01 02:21 UTC, annymsMthd commented
Not sure if the update to go 1.16 will mess up anything on your end. Let me know and I can just pull that out of this PR. This should fix kafmesh-gen on mac. So far I have it tested on bigsur. This also should let you use the latest version of protoc and the protoc-gen-go

2021-05-01 02:25 UTC, annymsMthd commented
Also I updated sarama. I'm going to be running this against kafka sometime this weekend and I can report back if I had any issues. If there is I can just remove those updates also.

2021-05-01 03:14 UTC, annymsMthd commented
#32 linking issue

2021-05-03 19:32 UTC, annymsMthd commented
Looks like this isn't exporting the grpc client/server with the protobuf generation. I need to take a look at that.

2021-05-03 19:55 UTC, annymsMthd commented
fixed

2021-05-07 19:55 UTC, annymsMthd commented
Got more of this up and running. Sarama 1.28 is breaking partitioning for joins and will put pods into a CrashLoopBackoff. Rolling back to 1.27 fixes the issue.. Looks like it still needs to be pinned there for now

2021-06-02 17:52 UTC, cuevaskoch requested changes

2021-06-02 17:52 UTC, cuevaskoch commented on go.mod
> +	github.com/Shopify/sarama v1.28.0
Can you update this to pin to 1.27 per [your comment](https://github.com/syncromatics/kafmesh/pull/33#issuecomment-834735534)?

2021-06-03 16:47 UTC, cuevaskoch commented on go.mod
> +	github.com/Shopify/sarama v1.28.0
Thanks!

2021-06-03 16:47 UTC, cuevaskoch approved these changes

2021-06-04 05:36 UTC, thzinc approved these changes

2021-07-28 16:36 UTC, merged